wiki/encyclopedia/urls.py
from django.urls import path


from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("NewPage", views.NewPage, name="NewPage"),
    path("Search", views.Search, name="Search"),
    path("RandomPage", views.RandomPage, name="RandomPage"),
    path("EditPage", views.EditPage, name="EditPage"),
    path("Wiki/<str:entry>", views.EntryPage, name="EntryPage"),
    path("Edit_Wiki/<str:title>", views.EditPage, name="EditPage"),
]

wiki/encyclopedia/templates/encyclopedia/EditPage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Page

{% endblock %}

{% block body %}
<style>
  input[type=text] {
       width: 200px;
       margin: 30px 0;
    }

  textarea[type=text] {
       margin: 30px 0;
       resize: none;
    }

</style>


<h3>{{message}}</h3>

<h2>{{title}}</h2>
<br>

<form  action="{% url 'encyclopedia:EditPage' title=title %}"  method="post" width=90% >
   {% csrf_token %}

   <h4>Change Encyclopedia Item :</h4>
   <textarea rows='13' cols='30' type="text" wrap="hard"  name="NewTextArea" >
      {{content | safe}}
   </textarea>

   <br>
   <form class="form-inline" style="position:relative ; top:15px" >
    <p>  <button type="submit"  class="btn btn-success">Save New Content</button>
          <button type="button" class="btn btn-danger">
          <a href="{% url 'encyclopedia:index' %}">Cancel</button>
    </p>
    </form>
</form>

<script>
function showNewTextArea() {
  var x = ""; var depois = "";
  var x = document.getElementById("content").value;
  document.getElementById("NewTextArea").innerHTML = x;
  var depois = document.getElementById("NewTextArea").value;
  alert(x);
}
</script>



{% endblock %}

wiki/encyclopedia/templates/encyclopedia/EntryPage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
     {{pagename}}
{% endblock %}

{% block body %}
{% csrf_token %}

<h3 style="color:red">{{message}}</h3>
<h1>{{title}}</h1>
<br>
<p>{{content | safe}}</p>
<br>
<form class="form-inline" style="position:relative; top:100px" method=post>
    <button type="submit" class="btn btn-success" >
        <a href="{% url 'encyclopedia:EditPage' title=title %}">Change Content</button>
    <button type="button" class="btn btn-danger">
        <a href="{% url 'encyclopedia:index' %}">Cancel</button>
</form>




{% endblock %}

wiki/encyclopedia/templates/encyclopedia/NewPage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New Page

{% endblock %}

{% block body %}

<style>
  input[type=text] {
       width: 200px;
       margin: 30px 0;
    }

  textarea[type=text] {
       margin: 30px 0;
       width:90%;

    }

</style>


<div class ="flex-container"  >
    <form  action= "{% url 'encyclopedia:NewPage' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <br>
        <label for="NewTitle"><b>Research Title Name :</b></label>
        <p>Please choose a word to tag your Item.<p>
        <input type="text" class="form-control" id="NewTitle" name="NewTitle" placeholder="Title for research" required>
        <p ><h2 style="color:red; background-color:pink">{{message}}<h2></p>
        <label for="NewContent"><b>Please describe your New Encyclopedia Item :</b></label>
        <textarea rows='13' cols='30' type="text" class="form-control"  id="NewContent" name="NewContent" placeholder="Place here your information" required ></textarea>

        <br>
        <form class="form-inline" style="position:relative; top:100px">
             <button type="submit" class="btn btn-success">Save</button>
             <button type="button" class="btn btn-danger"><a href="{% url 'encyclopedia:index' %}">Cancel</button>
        </form>
    </form>
</div>

<script>
    function goback()
       {
         window.history.back();
       }
</script>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/RandomPage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Random Page
{% endblock %}

{% block body %}


      <p> Sorted Number:  {{randonfile}} </p>
      <p> Title: {{title}}  </p>
      <p> Content: {{content}}  </p>


{% endblock %}

wiki/encyclopedia/templates/encyclopedia/Search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search Results
{% endblock %}


{% block body %}

    <h1> {{message}} </h1>


  <!--  <form action="{% url 'encyclopedia:Search' %}" method="post">-->
         {% csrf_token %}
         <h2>See all {{count}} files results for your search, {{seekword}}</h2>
         {%if count > 0 %}
         <h3>   Please click one for details:</h3>
         {%endif%}

         <ol>
         {% for titulo in TitulosAchados %}

            <h4 > <li> <a href= "{% url 'encyclopedia:EntryPage' entry=titulo %}" > {{ titulo }} </a> </li> <h4>

         {% endfor %}
          </ol>
  <!--  </form >-->

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia


{% endblock %}

<!--Criar link para todas as páginas -
    Index Page: Update index.html such that, instead of merely listing the names
    of all pages in the encyclopedia, user can click on any entry name to be taken
    directly to that entry page -->
{% block body %}
    <h1>All Pages</h1>
    <form action="{% url 'encyclopedia:index' %}" method="post">
        {% csrf_token %}
        <ul>
        {% for entry in entries %}
             <li><a href= "{% url 'encyclopedia:EntryPage' entry %}">{{ entry }}</a></li>

        {% endfor %}
        </ul>
    </form >





{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js"></script>
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form  action= "{% url 'encyclopedia:Search' %}" method="post">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" id="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:NewPage' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:RandomPage' %}">Random Page</a>
                </div>
                {%if page == "EntryPage"%}
                    <div>
                       <a href="{% url 'encyclopedia:EditPage'  %}" >Edit Title {{entry}}</a>
                    </div>
                {%endif%}
            {% block nav %}
            {% endblock %}
            </div>



           <div class="main col-lg-10 col-RandomPagemd-9">
               {% block body %}
               {% endblock %}
           </div>

            </div>

        </div>

    </body>
</html>